### PR TITLE
Updates README.md.

### PR DESCRIPTION
**Pull request by mjschranz**
- Properly lists each accessing method for adding request headers.

Could be just my own personal preference, but I noticed this when reading up on the project and it seemed off. Feel free to close if I'm way off on this.

### CODE REVIEW

**Comment by Nijikokun** [comment]
Aha, you have activated my trap card. It is actually correct, it does both, however if you feel this should be changed you can bring up the discussion on #41 

Source code for clarification: 
https://github.com/Mashape/unirest-nodejs/blob/master/index.js#L189

Also, I think if we are to change the readme it should perhaps be written like so:

```
Request.header(header[, value])
```

Thoughts?

**Comment by mjschranz** [comment]
I'm definitely more a fan of one unified method myself for dealing with these kinds of problems so :+1: for that. I think my confusion came from the fact that to me it present itself clearly in that specific section that all of those different options were available :)

Also down with using your suggestion as well since it will match your plans going forward.

**Comment by mjschranz** [comment]
I think the main question is removing all uses of `Request.headers` from the README or not if the goal going forward is to have only the single method of doing such.

**Comment by Nijikokun** [comment]
I think it will stay as `header` and `headers` I was debating with myself on making header throw an error should you pass an object, but whenever a tool does this, its implied that they understood what I meant... and would rather have had them just do the action.

**Comment by mjschranz** [comment]
Yep. Updated then!

**Comment by Nijikokun** [comment]
:+1:

**Pull request merged**
