### PR TITLE
update request version

### PR DESCRIPTION
**Pull request by bobjflong**
fixes https://github.com/Mashape/unirest-nodejs/issues/93

### CODE REVIEW

**Comment by jeffandersen** [comment]
Can we get this vulnerability closed? It's cascading into modules I depend on from this module.

@nijikokun maybe?

**Comment by davidgatti** [comment]
Can't wait.

**Comment by nijikokun** [comment]
:+1:

**Comment by nijikokun** [comment]
`0.5.1` has been released :)

**Pull request merged**
