### PR TITLE
Feature request timing

### PR DESCRIPTION
**Pull request by iCreateJB**
Update request version ( ~2.65.0 ) to allow for newer options, specifically request timing.

### CODE REVIEW

**Comment by iCreateJB** [comment]
@Nijikokun I noticed that I didn't bump the library version, ( 0.4.2 should go to 0.4.3 ), my apologies. Should I submit another PR to address this ?

**Comment by Nijikokun** [comment]
Yes

**Comment by Nijikokun** [comment]
Nope, I'll handle that I have a few more PRs to review first

**Comment by iCreateJB** [comment]
Sounds good, thanks.

**Pull request merged**
